### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by yana-tsylinska** [MastersAcademy/js-course#1]
1. Форкнуть репозиторий.
2. Создать папку внутри homeworks по типу **name.surname_githubUsername**, в ней создать папку для первой домашки - homework_1.
3. Заинсталить nodeJS >= v6.9.1 и npm >= 3.10.8 для работы сборщика.
4. Создать README.md в homework_1, в него записать версии nodeJS и npm.
5. Сделать npm init в homework_1.
6. Сделать pull request в главный репозиторий.

**Comment by yana-tsylinska** [comment]
**Useful links**
-  [Pro Git book](https://git-scm.com/book/en/v2)
-  [Node.js](https://nodejs.org/)
-  [Npm docs](https://docs.npmjs.com/)

**Comment by sasbor1** [comment]
ПРивіт. Підкажіть, брейнч свій чи мастер???

**Comment by sasbor1** [comment]
100500 apology only english

**Comment by yana-tsylinska** [comment]
на цьому етапі мастер

**Comment by idrummer83** [comment]
my pull-request dissapeared
