### ISSUE TITLE
Расписание на лекцию №2-3

### ISSUE THREAD

**Issue by smithua** [MastersAcademy/js-course#243]
Всем привет.
Чей пулреквест приняли, проходят на след занятие,
которое пройдет в **Четверг и Пятницу** в Оптима (там где была 1я лекция) в **18:30**.

Все вопросы задаем в чатик или в комментарии к этому issue.

**Группа - Четверг**

0: Aleksandr.Eremencko_Aleksandr-19991
1: Alexandr.Zhosan_Zhosan
2: Alexey.Gromyko_Alex-Gromyko
3: Alexey.Yavnyk_TheSorbex
4: Alexey.Zakruzhetslyi_RoRElessar
5: Andrii.Stashko_AndriiSV
6: Ann.Mokosii_algiaNost
7: Artem.Boboshko_ArtemBoboshko
8: Bogdan.Moskovchenko_Bogdan-Moskovchenko
9: Bohdan.Kostevych_BohdanKostevych
10: Danil.Bondarenko_Danil-Bondarenko
11: Daria.Vinogradina_Chernyava
12: Denys.Chykalo_DenysChykalo
13: Dima.Tachenko_DimaTachenko
14: Dmytro.Noskov_dvnoskov
15: Evgeniy.Gonchar_alcorine
16: Evgeniy.Nazarchuk_voo99
17: Igor.Ohrimenko_Ohrimenko1988
18: Igor.Skyba_IgorSkyba
19: Illia.Vodolad_Vodolad
20: Inna.Kravchenko_in4eg
21: Ivan.Artemenko_IvanArtemenko
23: Kate.Syrotchuk_KateSyrotchuk
24: Katya.Yatsenco_KatyaYatsenco
25: Kochergin.Sergej_argissa
28: Maksym.Gorbenko_WhatZ23
29: Maksym.Musiienko_Sempl
30: NatashaPavlenko_Noli29
31: Nikolay.Kushnir_Nimmerz
32: Oleg.Nikulin_nikulinn
33: Oleksandr.Kryzhnii_sashaTriceps
34: Olexandr.Datsenko_Sashok15
35: Olexiy.Velchenko_LefkaLefka
36: Pavel.Safran_Pashtet88
37: Roman.Tkachenko_RomanTkachenkoUA
38: Roman.Vertyporoh_Awake123
39: Sergey.Maystrenko_sergeymays
42: Sergiy.Tkachenko_JohnnyPikoneron
43: Tanya.Tokareva_EmilyHarkness
44: Urakov.Serhey_Elmarfdk
45: Vadim.Mendelson_Mendels0n
46: Vitali.Polishchuk_getbrainme
47: Vitaliy.Barvinok_Cvetkow
48: Vitaliy.Kryzhevskiy_Vkryzha
49: Vladimir.Laut_Laut
51: Vladymyr.Mitin_k57112
52: Volodymyr.Glova_VolodymyrGlova
53: Volodymyr.Kravchuk_PulsarV
54: Yaroslav.Kuznetsov_fevergame
56: Yuri.Ostapenko_wiNgeRf0rN1ceE
57: aleksandr.karpan _Fawell-AK
59: alexandr.soldat_AlexandrGrigorievich
60: alexey.efimenko_AlexeyVE
61: alla.kovalenko_allakovalenko
63: andrew.starov_sadboyandrew
64: andrew.syrotchuk_syrotchukandrew
65: andrey.litcheveckiy_andrey34-77
66: andrey.melnichenko_BJIAST
67: andrii.malamuzh_prolop
129: vsevolod.lukovnikov_ss200010
76: demian.kurilenko_mistes
128: vova.mahdych_VladymyrVr
104: pasha.fudko_darkwoolf10
136: yuriy.chaban_YuriyChaban
122: vlad.gevel_bubman
90: keresa.oleksand_Kepeca
83: evgeniy.loginov_ev-loginov
102: olha.bezpalchuk_OlhaBezpalchuk
95: oleksand.velykyi_BigIS
94: nicholas.chertkov_Rivalmist
135: yurii.vishnevskii_yuriivishnevskii
99: oleksii.bratenkov_OleksiiBratenkov

**Группа - Пятница**

68: andriy.kaminskiy_kamandand
69: andriy.kornienko_dr0n508
70: ann.prysiazhniuk_annprisyazhnyuk
71: anton.luzhanovskyi_diss1dent
72: anton.triputen_Nako68l
73: artem.luzhanovskyi_ucozlab
74: bogdan.bezpoyasniy_incarnus
75: boris.larioshin_larioshin-boris
77: dima.shifrin_shifa87
78: dima.vovkodav_FredyYy
79: dmitriy.datsenko_DmitriyDats
80: dmitriy.rusenko_vitaminchikkk
81: dmitriy.tarasenko_gamid88
82: dmytro.shpylko_dmytroshpylko
84: gaik.grigoryan_DjGaik
85: igor.shkliar_shkigor
86: igor.sokurenko_praetorianlive
87: igor.zalevskiy_igorzalevskiy
88: ihor.tkachuk_ihortkachuk
89: kateryna.chepurna_niampire
91: ludmila.petchik_Lutiks2
92: lyudmila.bilazerskaya_murzikvasya
93: max.marchenko_maxmar
96: oleksandr.gonchar_alexgoncharcherkassy
97: oleksandr.kurov_alextriam
98: oleksandr.matskevych_matskevych
100: oleksii.moroz_morale22
101: olga.gulenko_OlgaGulenko
103: olya.dowgal_olyadowgal
105: popovych.bohdan_Rootwar
106: rostislav.yemelyanow_yemelyanow-ross
107: ruslana.podsyvalova_RPodshyvalova
108: sasha.nizovoy_AlexNizovoy
109: segey.voloshin_GeckVel
110: sergey.belazerskiy_lordsenya
111: sergey.dragan_s-dragan
112: sergey.ripchanskiy_Ripchanskiy
113: sergey.romovich_RomovichSergey
114: svitlana.seleznova_seleznovasvs
115: tatyana.rozhnova_tanyaro
116: valentin.tiutiunnyk_valentayzer
117: viacheslav.karpenko_keyhit
118: viacheslav.lepetukha_lucky85
119: vitalii.astafiev.vilfat
120: vitalii.orlvskyi_vitaliaa
121: vitalii.yatsenko_TooFed
123: vlad.goncharenko_RhinoGrey
124: vlad.smirnov_vladsmirnov
125: vladimir.varavva_Acid-base
126: vladislav.sheludko_vladislavsheludko
127: volodymyr.kravchenko_Patriarh22
130: vyacheslav.prokopenko_partosup
131: yana.chorna_YanaChornaya
132: yaroslav.stetsenko_yaroslav-stetsenko
133: yrij.kovtun_Sckorobej
134: yuri.zheludkov_Yuricoden
137: yuriy.lyashenko_idrummer83
55: Yaroslav.Mokhurenko_yarik335
62: anatoliy.bida_Razboy
27: Liudmila.Sobchenko_L-Sobchenko
41: Sergiy.Reva_SiegfriedIX
22: Julya.Litvin_julyalitvin
26: Konstantin.Tsarenko_KTsarenko
58: alexandr.parkhomenko_Parhomenko
50: Vladislav.Kim_zimirkim
40: Sergii.Bondarenko_Sergii5854

**Comment by yarik335** [comment]
а можно прийти в пятницу (я попадаю на четверг папка:yaroslav.mokhurenko)? 
P.S. могу поменяться кто хочет

**Comment by ss200010** [comment]
yarik335 , я готов махнуться)) в пятницу уезжаю из города

**Comment by idrummer83** [comment]
ссылку на чат можно??

**Comment by smithua** [comment]
@idrummer83 http://dsh.re/77ab3

**Comment by smithua** [comment]
Ссылка находится в шапке README

**Comment by Mistes** [comment]
Перекиньте меня в групу Четверг. demian.kurilenko.mistes  76

**Comment by VladymyrVr** [comment]
Пожалуйста перекиньте меня в групу на четвер  vova.mahdych_VladymyrVr пожалуйста

**Comment by darkwoolf10** [comment]
перенесите меня на чт(не в 1 подгруппу, а просто на 1 раз)

**Comment by Yurii-Chaban** [comment]
йду в четвер

**Comment by bubman** [comment]
йду в четвер

**Comment by maxmar** [comment]
### дайош четвер

ну пазязь))

**Comment by ev-loginov** [comment]
Можно тоже перекинуть в группу на четверг evgeniy.loginov_ev-loginov

**Comment by olha-bezpalchuk-moc** [comment]
Можна, будь ласка, теж приєднатися до групи четверга?
102: olha.bezpalchuk_OlhaBezpalchuk

**Comment by Olegborodko** [comment]
Скажите, а можно ходить если не здал дом. задание? .. Интересно что будет на лекциях .. а если с меня 5 шеколадок? )

**Comment by Razboy** [comment]
62: anatoliy.bida_Razboy мене будь ласка на пятницю

**Comment by BigIS** [comment]
Іду в четверг oleksand.velykyi_BigIS

**Comment by L-Sobchenko** [comment]
Якщо можна, мене на п'ятницю Liudmila.Sobchenko_L-Sobchenko

**Comment by SiegfriedIX** [comment]
Можно и меня на пятницу? Sergiy Reva

**Comment by rusteth** [comment]
Перекиньте, пожалуйста, на четверг
yurii.vishnevskii_yuriivishnevskii

**Comment by Rivalmist** [comment]
Переместите на четверг, пожалуйста 
94: nicholas.chertkov_Rivalmist

**Comment by julialitvin** [comment]
Будь ласка, перенесіть до групи у п'ятницю.
22: Julya.Litvin_julyalitvin

**Comment by Kepeca** [comment]
Будь ласка, перенесіть до групи у четверг.
keresa.oleksand_Kepeca

**Comment by OleksiiBratenkov** [comment]
а можно меня на четверг ? bratenkov.oleksii

**Comment by grifanik** [comment]
Если эта ссылка есть в Issues, но моего имени нет в списке, то что это значит?

**Comment by grifanik** [comment]
Не приняли, к сожалению.

**Comment by KTsarenko** [comment]
Просьба перенести на пятницу 26: Konstantin.Tsarenko_KTsarenko. Спасибо.

**Comment by Parhomenko** [comment]
Здравствуйте. Очень большая просьба перенести 58: alexandr.parkhomenko_Parhomenko на пятницу. Заранее спасибо.

**Comment by zimirkim** [comment]
Перенесіть на п'ятницю, будь ласка, 50: Vladislav.Kim_zimirkim

**Comment by sergii-bondarenko-i** [comment]
Доброго дня  
Прохання перенисти на п'ятницю 
40: Sergii.Bondarenko_Sergii5854

**Comment by RhinoGrey** [comment]
Меня пожалуйста на четверг.
vlad.goncharenko_RhinoGrey
